### PR TITLE
fix component casting, allow <VuetifyResource/> to work as well, closes #22

### LINKED ISSUE #22: <VuetifyUpload/> is not working

### PR DESCRIPTION
**Pull request by ricardovanlaarhoven**

### CODE REVIEW

**Review by koenhoeijmakers — APPROVED** [review]

File: playground/App.vue [hunk 1]
```diff
@@ -1,13 +1,30 @@
...
-            <vuetify-upload
+        <v-container>
+            <VuetifyUpload
                 label="Images for the slideshow"
                 :max="4"
                 can-delete
                 accept="image/*"
                 color="accent"
-            ></vuetify-upload>
+            />
```
Comment (Deluze) [inline playground/App.vue:10]: Is this still supposed to be here? Because now you will have 2 exactly the same Vuetify Upload's grouped together :thinking:

Comment (ricardovanlaarhoven) [reply playground/App.vue:10]: Yeah i wanted to show both that possibilities worked
